#!/bin/bash

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
NC='\033[0m' # No Color


printf "${Cyan}Update and install necessary libs and GPG keys${NC}\n"

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt autoremove

sudo apt-get install -y \
  ca-certificates \
  curl \
  gnupg \
  lsb-release \
  qemu-guest-agent

sudo systemctl start qemu-guest-agent

sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

printf "${Cyan}Update sources.list${NC}\n"
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

printf "${Cyan}Docker installing:${NC}\n"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

apt-cache madison docker-ce

printf "${Green}Testing Docker container under the root:${NC}\n"
sudo docker run hello-world

printf "${Green}Adding current user to the Docker group:${NC}\n"
sudo usermod -aG docker $USER

newgrp docker

printf "${Green}Testing Docker container under the %s:${NC}\n" "${USER}"
docker run hello-world

printf "${Cyan}Docker compose installing:${NC}\n"
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

printf "${Green}Testing Docker compose installation:${NC}\n"
docker-compose --version

printf "${Green}Gitlab Runner installation:${NC}\n"
sudo curl -L --output /usr/local/bin/gitlab-runner "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64"
sudo chmod +x /usr/local/bin/gitlab-runner
sudo useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash
sudo gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
sudo gitlab-runner start

sudo rm /home/gitlab-runner/.bash_logout
